Criando a tela de Home
DavidGomes7/medistation pull request #13
Opened 2024-12-04 03:41 UTC by NionBr

2024-12-04 10:26 UTC, andrezin96 requested changes

2024-12-04 10:26 UTC, andrezin96 commented on lib/modules/home/components/medi_drawer.dart
> +        children: [
Seria melhor usar um ListView, a Column quebra se a tela quebra se não tiver o tamanho pra exibir todos os itens.

2024-12-04 10:26 UTC, andrezin96 commented on lib/modules/home/components/medi_drawer.dart
> +              child: Column(
Existe um componente chamado DrawerHeader,

2024-12-04 10:26 UTC, andrezin96 commented on lib/modules/home/controller/home_cubit.dart
> +
Aqui seria interessante ter um método chamado init por exemplo, setando a url, e ser chamado na criação pa página. No caso na HomePage. Seria interessante uma abstração desse JustAudio, e chama ela e não package direto, ou um serviço chamado MediPlayer.

2024-12-04 10:26 UTC, andrezin96 commented on lib/modules/home/controller/home_cubit.dart
> +    countDownController.start();
O emit é sempre a última linha. Aqui você ta emitimdo um estado que ainda não aconteceu.

2024-12-04 14:06 UTC, NionBr commented on lib/modules/home/controller/home_cubit.dart
> +
A abstração é desnecessária, porque o package só é usado dentro do módulo home

2024-12-04 15:23 UTC, andrezin96 commented on lib/modules/home/controller/home_cubit.dart
> +
Abstração é um princípio do SOLID, isso deveria ser um serviço, já que não será usado só na home.

2024-12-04 15:42 UTC, DouglasSilvaa commented on lib/modules/home/controller/home_cubit.dart
> +
Os priincípios do SOLID tem que ser usados com cautela para não se ter excesso de arquitetura, que o caso aqui

2024-12-04 23:58 UTC, DavidGomes7 approved these changes

2024-12-05 00:00 UTC, DavidGomes7 approved these changes

2024-12-05 01:06 UTC, andrezin96 approved these changes

2024-12-05 01:07 UTC, merged