#03-MEDISTATION-Criando a tela tips
DavidGomes7/medistation pull request #17
Opened 2024-12-10 01:17 UTC by DavidGomes7

2024-12-11 20:47 UTC, andrezin96 requested changes

2024-12-11 20:47 UTC, andrezin96 commented on lib/modules/tips/controller/tips_cubit.dart
É uma boa prática manter o nome do cubit seguido da descrição, sem colocar state no final. Ex.: TipsInitial( )

2024-12-11 20:47 UTC, andrezin96 commented on lib/modules/tips/controller/tips_state.dart
.

2024-12-11 20:47 UTC, andrezin96 commented on lib/modules/tips/components/tips_template.dart
> +          crossAxisAlignment: CrossAxisAlignment.start,
Aqui você pode usar um ListView, no lugar do Scrollview a da Column. Dessa forma funciona, mas com o ListView é um widget a menos pra ser processado.

2024-12-11 20:47 UTC, andrezin96 commented on lib/modules/tips/components/tips_template.dart
> +              content: 'Encontre um lugar tranquilo e confortável onde você não será incomodado. Criar um espaço dedicado à meditação promove a concentração, estabelece rotina, reduz distrações e pro
Aqui recomendo você criar um arquivo de constants. Dentro da pasta lib/core/constants, adiciona todos esses textos lá e chama na tela. Dessa forma também está certo, é só pra deixar maís legível e organizado.

2024-12-11 20:47 UTC, andrezin96 commented on lib/modules/tips/components/tips_template.dart
> +              content: 'O tempo é importante porque pode impactar a qualidade e a eficácia da sua prática. O ritmo de cada pessoa varia - algumas pessoas ficam mais alertas e receptivas pela manhã, e
No tipsbox você pode adicionar uma margin 10 no top ou symetric vertical 20, com isso da pra remover esses sizedbox.

2024-12-12 02:03 UTC, andrezin96 approved these changes

2024-12-22 17:07 UTC, NionBr approved these changes

2024-12-22 17:07 UTC, merged